name: Continuous integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: pip3 install --no-cache-dir -r requirements-dev.txt
      - name: Execute unit tests
        run: pytest tests
  test_demos_no_error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Test the function call demo
        run: python3 demos/demo_fnc_calls.py
      - name: Test the string to pathlib demo
        run: python3 demos/demo_str_to_pathlib.py demos/the_planets.txt
      - name: Test the pathlib to string demo
        run: python3 demos/demo_pathlib_to_str.py .. . .github/workflows demos strath tests
  test_pypi_package_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Test the build
        run: python3 .github/workflows/test_pypi_package_build.py
